### ISSUE TITLE
multimask

### ISSUE THREAD

**Issue by murka** [RonaldJerez/vue-input-facade#18]
Hey, how to change mask for:
1) when I write "+1 (732) 123-4567", @vue-input-facade rewrite to "+17321234567".
2) when I write "(732) 123-4567", it rewrites to "+17321234567"
3) when I write "1 (732) 123-4567" it rewrites to "+17321234567"

I tried use @vue-the-mask, but I didn’t succeed.

**Comment by RonaldJerez** [comment]
When you say “rewrite” I’m going to assume you mean return value and not what’s shown on the screen.

You can use this mask “+1 ### ### - ####“ and set prefill to true.  But you won’t get the +1 as part of your return value because that’s static. So you can either add that yourself where ever you need it, or use a formatting function to add it.

```
<input-facade mask="+1 (###) ### - ####" v-model="value" :masked="masked" prefill />
```
