### ISSUE TITLE
question: when using multiple masks, what determines the priority?

### ISSUE THREAD

**Issue by pancake-boy** [RonaldJerez/vue-input-facade#25]
masks = "+### ########", "+## ########"

When i type '12' then '3', i get '+12 3', so it seems to be matching the 2nd mask first.
Is there a way to match the 1st one instead?

**Comment by RonaldJerez** [comment]
Hi, the mask array gets sorted by length internally. This was inherited from vue the mask. After that the priority is which ever mask gives you the most amount of user typed data. 

So in your example, the 2nd mask is shorter in length so it gets evaluated first. Which makes sense because otherwise it will never be used since the first mask will always work for whatever numbers the user types in.
