### ISSUE TITLE
Directive not fully working with input[type="number"]

### ISSUE THREAD

**Issue by ErickPetru** [RonaldJerez/vue-input-facade#27]
**Describe the bug**
When using `v-facade` directive with a `#####` mask (allowing only numbers) inside an `<input type="number />` tag, the mask works partially, avoiding letters and other non numeric chars, but incorrectly allowing some chars.

It also happens with a custom token based mask, avoiding all chars not in the token but allowing those same chars.

The chars always allowed on `type="number"` are: `e` `+` `-` `,` `.`

**To Reproduce**
Just put `type="number"` in the `input` element.
Here's a sandbox to easily test the issue: https://codesandbox.io/s/vue-input-facade-tests-qnt2z?file=/src/App.vue.

**Expected behavior**
Follow the mask behavior in the same way as it works on `<input type="text" />`.

**Additional context**
Yes, I know I could just remove the `type=["number"]`, but keeping it is important for accessibility and for UX (since many mobile browsers can show a dedicated numeric virtual keyboard only for `type=["number"]`).

**Comment by RonaldJerez** [comment]
Hi, thanks for the bug report. There is no special handling for field types so not really sure why those characters are been allowed.  However it is worth noting that only certain fields can be supported due to javascript spec limitations with cursor positioning methods only been available on certain field types, and type=number is not one of them. 

As [defined here](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange)
>Note that accordingly to the WHATWG forms spec selectionStart, selectionEnd properties and setSelectionRange method apply only to inputs of types text, search, URL, tel and password. Chrome, starting from version 33, throws an exception while accessing those properties and method on the rest of input types.

I will take a look regardless but I have a feeling its some spec/browser limitation on those input types.

**Comment by RonaldJerez** [comment]
Finally got some free time and looked closer into this.  Currently the browsers do their own validation on inputs with specific types.  In this case for number for example if you were to type "1".  Follow by a "."  the browser is showing "1." in the field however it is just sending a "1" as the input value to the input handler.  Now to our code the value hasn't changed since it is still just the same "1" as before typing the ".", because of that we do not act on the input and we don't emit another input event so the browser can re-render it.   In the case of other characters for example if you were to type a letter, the browsers despite showing "1a" it is sending an empty value to the code logic.  I assume this is because the field's current value is not an actual number.

So given the above, the browsers are doing their own special handling of these inputs and not passing the true value to the code as represented on the fields.  So its not something I can support or work around.

I will put a note on the readme of not been able to support special inputs.
