### ISSUE TITLE
Error with conditional slot content

### ISSUE THREAD

**Issue by deraw** [RonaldJerez/vue-input-facade#29]
**Describe the bug**
Error with `v-if` in `VTextField` slot's content where the directive is binded

**To Reproduce**
[Reproduction link](https://codepen.io/Deraw/pen/mdrbJoN?editors=1111)

```vue
<div class="input" v-facade="'##'">
  <v-text-field v-model="input">
    <template #prepend>
      <span v-if="toggle" />
    </template>
  </v-text-field>
</div>
```

1. Enter text in the `VTextField`, it works as expected (can only enter numbers)
2. Click the "toggle" button
3. Enter text again
4. See error in console, the directive is broken

```
"[Vue warn]: Error in directive facade update hook: 'TypeError: Cannot destructure property 'config' of 't2[a]' as it is undefined.'
```

**Expected behavior**
The directive doesn't break when using `v-if` in slot content

**Workaround**
When using `v-show` instead of `v-if` this issue doesn't occurs

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86

**Additional context**
It seems that the config is lost, `core.updateValue` is called in [the update hook](https://github.com/RonaldJerez/vue-input-facade/blob/master/src/directive.js#L23). Inside, the config id read `let { config, oldValue } = el[CONFIG_KEY]` but it doesn't exists anymore

**Comment by RonaldJerez** [comment]
This is not a v-facade bug.  When you use the directive in a none input element/component it will just search its children and attach to the first input it finds.  However your v-if is causing the Dom elements containing the input to be destroyed and recreated.  In contrast v-show only shows/hides without destroying the elements, that's what it works with v-show.

Since you are attaching v-facade in the outer div, when the inter v-if destroys the inner elements it is removing the input context that v-facade is expecting.   You will need to refactor your code so you do not attach v-facade to an outer element that won't be re-render due to the v-if.

**Comment by deraw** [comment]
Hi @RonaldJerez,

Thank you for your reply and your explanation!
