### ISSUE TITLE
Can i make the mask always shown?

### ISSUE THREAD

**Issue by dexcell** [RonaldJerez/vue-input-facade#8]
E.g i want to have mask for phone number
Instead of waiting user to write their first digit first, i want to show +1 as prefix in my input indefinitely,

Is it possible right now with this plugin?

Thanks

**Comment by RonaldJerez** [comment]
Hi @dexcell,  currently you can't do that.  My use case actually didn't want that particular functionality so it was purposely removed.  It can easily be added back on as a prop if you need it.  I'll mark this issue as a feature request and try to get that in to the next release.

**Comment by RonaldJerez** [comment]
@dexcell See above comment, I was just about to release an update to the beta version so I included this in there as well, give it a shot and see if it works for you.

**Comment by dexcell** [comment]
Hi thank you,

It's working good,
but i found there is a problem if you use `(` characters, probably the lib thinks its prepended chars. maybe better let the user write what the prepended string manually via the props?
````
<input-facade :prepend="true" mask="+1 (###) ###-####" name="phoneNumber" type="tel" />
````

**Comment by RonaldJerez** [comment]
That’s how it works, any characters at the beginning of the mask string that is not part of the token set will be shown Initially. In your example the “+1 (“ would be shown and the use can just start typing the numbers.

Accepting it as a prop will start making it more complex because the lib would need to start taking that into account.
